version: "3.8"
name: langchain-extract

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    env_file:
      - .local.env
    ports:
      - "8000:8000" # Backend is accessible on localhost:8100
    volumes:
      - ./backend:/backend